<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>


    <xacro:property name="base_length" value="0.5"/>
    <xacro:property name="base_width" value="0.3"/>
    <xacro:property name="base_height" value="0.009"/>
    <!-- <xacro:property name="base_mass" value="20.0"/> -->
    <xacro:property name="wheel_radius" value="0.0325"/>
    <xacro:property name="wheel_length" value="0.026"/>
    <xacro:property name="wheel_offset_x" value="0.22"/>
    <xacro:property name="wheel_offset_y" value="0.312"/>
    <xacro:property name="wheel_offset_z" value="0.0125"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>


    <!-- BASE_FOOTPRINT LINK -->
    <link name="base_footprint">
    </link>

    <!-- BASE LINK -->

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}"
                           xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </link>

    <gazebo reference="base_link">
        <material>Gazebo/Orange</material>
    </gazebo>


    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>


    <!-- wheel LINK -->

    <xacro:macro name="wheel" params="prefix">
        <link name="${prefix}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="blue" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <xacro:cylinder_inertia m="1.0"  r="${wheel_radius}" h="${wheel_length}"
                                        xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>             
        </link>
    </xacro:macro>



 

    <!-- FRONT_LEFT WHEEL LINK -->
    <xacro:wheel prefix="front_left" />

    <gazebo reference="front_left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="front_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_left_wheel"/>
        <origin xyz="${base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0"/>
    </joint>

        <!-- Transmission for rear_left_wheel -->
    <transmission name="front_left_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="front_left_wheel_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="front_left_motor">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    </transmission>

    <!-- Gazebo plugin interface -->
    <gazebo>
    <plugin name="front_left_wheel_controller" filename="libgazebo_ros_joint_control.so"/>
    </gazebo>


    <!-- FRONT_RIGHT WHEEL LINK -->
    <xacro:wheel prefix="front_right" />

    <gazebo reference="front_right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="front_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_right_wheel"/>
        <origin xyz="${base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0"/>
    </joint>

        <!-- Transmission for rear_left_wheel -->
    <transmission name="front_right_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="front_right_wheel_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="front_right_motor">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    </transmission>

    <!-- Gazebo plugin interface -->
    <gazebo>
    <plugin name="front_right_wheel_controller" filename="libgazebo_ros_joint_control.so"/>
    </gazebo>



    <!-- REAR_LEFT WHEEL LINK -->
    <xacro:wheel prefix="rear_left" />

    <gazebo reference="rear_left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="rear_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rear_left_wheel"/>
        <origin xyz="${-base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0"/>
    </joint>

    <!-- Transmission for rear_left_wheel -->
    <transmission name="rear_left_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="rear_left_wheel_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="rear_left_motor">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    </transmission>

    <!-- Gazebo plugin interface -->
    <gazebo>
    <plugin name="rear_left_wheel_controller" filename="libgazebo_ros_joint_control.so"/>
    </gazebo>


    <!-- REAR_RIGHT WHEEL LINK -->
   <xacro:wheel prefix="rear_right" />

    <gazebo reference="rear_right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="rear_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rear_right_wheel"/>
        <origin xyz="${-base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0"/>
    </joint>

        <!-- Transmission for rear_left_wheel -->
    <transmission name="rear_right_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="rear_right_wheel_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="rear_right_motor">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    </transmission>

    <!-- Gazebo plugin interface -->
    <gazebo>
    <plugin name="rear_right_wheel_controller" filename="libgazebo_ros_joint_control.so"/>
    </gazebo>


    



</robot>